services:
  sant_app:
    container_name: sant_app
    build: .
    ports:
      - "3000:3000"
    links:
      - "sant_mongo:mongohost"

  sant_mongo:
    container_name: sant_mongo
    image: mongo:latest
    ports:
      - "27017:27017"
